include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart

linter:
  rules:
    prefer_relative_imports: true
    always_declare_return_types: true
    avoid_multiple_declarations_per_line: true
    directives_ordering: true
    no_logic_in_create_state: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    prefer_const_constructors_in_immutables: true
    prefer_function_declarations_over_variables: true
    unnecessary_lambdas: true
    avoid_returning_null: true
    avoid_bool_literals_in_conditional_expressions: true
    unnecessary_late: true
    unnecessary_await_in_return: true
    require_trailing_commas: true
    prefer_interpolation_to_compose_strings: true
    cancel_subscriptions: true
    avoid_returning_null_for_void: true
    type_annotate_public_apis: true
