// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY9jXcqbmDBWBYV3gjnNx8UYrEwzkpiGQ',
    appId: '1:678633298408:android:c2c9ebb8598494ccf92c5d',
    messagingSenderId: '678633298408',
    projectId: 'chat-app-853b1',
    storageBucket: 'chat-app-853b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeWHpJTPG1oguhlkcfWXaIwRFLUCgD4Wg',
    appId: '1:678633298408:ios:c0a24b33f1bd0313f92c5d',
    messagingSenderId: '678633298408',
    projectId: 'chat-app-853b1',
    storageBucket: 'chat-app-853b1.appspot.com',
    iosClientId: '678633298408-htenvbmqt0ei4k0jglj3i2ns5b8h748q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatClientApp',
  );
}
